---
AllCops:
  TargetRubyVersion: 2.4
  
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - Rakefile

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*
